# Generated by Django 2.1.7 on 2019-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='Contact_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='hospitals',
            table='Hospital',
        ),
    ]
