# Generated by Django 2.1.7 on 2019-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20190609_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='Hospital_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
