# Generated by Django 2.1.7 on 2019-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('disease_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Symptoms', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
