# Generated by Django 2.1.7 on 2019-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Symptoms', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Disease',
            },
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
    ]
