# Generated by Django 2.1.7 on 2019-06-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('Patients_Num', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(max_length=50)),
                ('Contacts', models.CharField(blank=True, max_length=10, null=True)),
                ('Disease', models.TextField(blank=True, max_length=5, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctors')),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospitals')),
            ],
        ),
    ]
