# Generated by Django 2.1.7 on 2019-06-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Disease'),
        ),
        migrations.AlterModelTable(
            name='patients',
            table='Patients',
        ),
    ]
