# Generated by Django 2.1.7 on 2019-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20190609_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Patients_Num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
