# Generated by Django 2.1.7 on 2019-06-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):



    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('Enroll_Num', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Contacts', models.CharField(blank=True, max_length=10, null=True)),
                ('Qualification', models.TextField(blank=True, max_length=5, null=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospitals')),
            ],
        ),
    ]
