# Generated by Django 2.1.7 on 2019-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='doctors',
            table='Doctors',
        ),
    ]
